name:                http-request-log-service
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/http-request-log-service#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - aeson
  - aeson-pretty
  - base >= 4.7 && < 5
  - bytestring
  - http-types
  - time
  - utf8-string
  - wai
  - warp

executables:
  http-request-log-service:
    source-dirs:      src
    main:             Main.hs
